//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Properties.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s ActivityStatus..
        /// </summary>
        internal static string ActivityStatusIsEmpty {
            get {
                return ResourceManager.GetString("ActivityStatusIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the config Id.
        /// </summary>
        internal static string ConfigIdIsEmpty {
            get {
                return ResourceManager.GetString("ConfigIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the config Value.
        /// </summary>
        internal static string ConfigValueIsEmpty {
            get {
                return ResourceManager.GetString("ConfigValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s DiscountAmount..
        /// </summary>
        internal static string DiscountAmountIsEmpty {
            get {
                return ResourceManager.GetString("DiscountAmountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s AssessmentValue..
        /// </summary>
        internal static string DiscountAssessmentValueIsEmpty {
            get {
                return ResourceManager.GetString("DiscountAssessmentValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s Description..
        /// </summary>
        internal static string DiscountDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("DiscountDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount&apos;s name exceeded maximum length.
        /// </summary>
        internal static string DiscountNameExceededMaxLength {
            get {
                return ResourceManager.GetString("DiscountNameExceededMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s Name..
        /// </summary>
        internal static string DiscountNameIsEmpty {
            get {
                return ResourceManager.GetString("DiscountNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s VendorId..
        /// </summary>
        internal static string DiscountVendorIdIsEmpty {
            get {
                return ResourceManager.GetString("DiscountVendorIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s EndDate..
        /// </summary>
        internal static string EndDateIsEmpty {
            get {
                return ResourceManager.GetString("EndDateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Address..
        /// </summary>
        internal static string PointOfSaleAddressIsEmpty {
            get {
                return ResourceManager.GetString("PointOfSaleAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Latitude..
        /// </summary>
        internal static string PointOfSaleLatitudeIsEmpty {
            get {
                return ResourceManager.GetString("PointOfSaleLatitudeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Longitude..
        /// </summary>
        internal static string PointOfSaleLongitudeIsEmpty {
            get {
                return ResourceManager.GetString("PointOfSaleLongitudeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Name..
        /// </summary>
        internal static string PointOfSaleNameIsEmpty {
            get {
                return ResourceManager.GetString("PointOfSaleNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s StartDate..
        /// </summary>
        internal static string StartDateIsEmpty {
            get {
                return ResourceManager.GetString("StartDateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag&apos;s name exceeded maximum length.
        /// </summary>
        internal static string TagNameExceededMaxLength {
            get {
                return ResourceManager.GetString("TagNameExceededMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Address..
        /// </summary>
        internal static string VendorAddressIsEmpty {
            get {
                return ResourceManager.GetString("VendorAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Description..
        /// </summary>
        internal static string VendorDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("VendorDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Email..
        /// </summary>
        internal static string VendorEmailIsEmpty {
            get {
                return ResourceManager.GetString("VendorEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor&apos;s name exceeded maximum length.
        /// </summary>
        internal static string VendorNameExceededMaxLength {
            get {
                return ResourceManager.GetString("VendorNameExceededMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Name..
        /// </summary>
        internal static string VendorNameIsEmpty {
            get {
                return ResourceManager.GetString("VendorNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Phone..
        /// </summary>
        internal static string VendorPhoneIsEmpty {
            get {
                return ResourceManager.GetString("VendorPhoneIsEmpty", resourceCulture);
            }
        }
    }
}
