//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Properties.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s ActivityStatus..
        /// </summary>
        internal static string ActivityStatus {
            get {
                return ResourceManager.GetString("ActivityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s DiscountAmount..
        /// </summary>
        internal static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s AssessmentValue..
        /// </summary>
        internal static string DiscountAssessmentValue {
            get {
                return ResourceManager.GetString("DiscountAssessmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s Description..
        /// </summary>
        internal static string DiscountDescription {
            get {
                return ResourceManager.GetString("DiscountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s Name..
        /// </summary>
        internal static string DiscountName {
            get {
                return ResourceManager.GetString("DiscountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s VendorId..
        /// </summary>
        internal static string DiscountVendorId {
            get {
                return ResourceManager.GetString("DiscountVendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s EndDate..
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Address..
        /// </summary>
        internal static string PointOfSaleAddress {
            get {
                return ResourceManager.GetString("PointOfSaleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Latitude..
        /// </summary>
        internal static string PointOfSaleLatitude {
            get {
                return ResourceManager.GetString("PointOfSaleLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Longitude..
        /// </summary>
        internal static string PointOfSaleLongitude {
            get {
                return ResourceManager.GetString("PointOfSaleLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the pointOfSale&apos;s Name..
        /// </summary>
        internal static string PointOfSaleName {
            get {
                return ResourceManager.GetString("PointOfSaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the discount&apos;s StartDate..
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Address..
        /// </summary>
        internal static string VendorAddress {
            get {
                return ResourceManager.GetString("VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Description..
        /// </summary>
        internal static string VendorDescription {
            get {
                return ResourceManager.GetString("VendorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Email..
        /// </summary>
        internal static string VendorEmail {
            get {
                return ResourceManager.GetString("VendorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Id..
        /// </summary>
        internal static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Name..
        /// </summary>
        internal static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the vendor&apos;s Phone..
        /// </summary>
        internal static string VendorPhone {
            get {
                return ResourceManager.GetString("VendorPhone", resourceCulture);
            }
        }
    }
}
