# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

COPY . .

RUN dotnet restore "WebApi/WebApi.csproj"

# copy and publish app and libraries
COPY . .

# DB Update
RUN echo 'export PATH="$PATH:/root/.dotnet/tools"' >>  ~/.bash_profile
RUN dotnet tool install --global dotnet-ef
RUN export PATH="$PATH:/root/.dotnet/tools"


WORKDIR /source/WebApi
RUN sleep 5;/root/.dotnet/tools/./dotnet-ef database update

# Build
RUN dotnet build "WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApi.csproj" -c Release -o /app/publish

# Run
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 44395 44396

ENTRYPOINT ["dotnet", "WebApi.dll"]
